[phases.setup]
nixPkgs = ["php81", "php81Extensions.mysqlnd", "php81Extensions.mysqli", "php81Extensions.pdo", "php81Extensions.pdo_mysql", "php81Extensions.mbstring", "php81Extensions.gd", "php81Extensions.intl", "php81Extensions.xml", "php81Extensions.curl", "php81Extensions.zip"]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
cmd = "php -S 0.0.0.0:$PORT"
