[phases.setup]
nixPkgs = ["php74", "php74Extensions.mysqlnd", "php74Extensions.mysqli", "php74Extensions.pdo", "php74Extensions.pdo_mysql", "php74Extensions.mbstring", "php74Extensions.gd", "php74Extensions.intl", "php74Extensions.xml", "php74Extensions.curl", "php74Extensions.zip"]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
cmd = "php -S 0.0.0.0:$PORT"